/**
 * Qa admin api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: admin
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/* tslint:disable:no-unused-variable member-ordering max-line-length interface-name */

import * as models from './models';

export interface TableMonitor {
    tableNumber?: string;
    status?: TableMonitor.StatusEnum;
    waitingItemId?: number;
    reservationId?: string;
    registrationId?: number;
    partySize?: number;
    membership?: models.MembershipInfo;
    nextReservationTime?: string;
    assignmentTime?: string;
    registrationTime?: string;
    estimatedReleaseTime?: string;
    waiter?: models.WaiterMonitor;
    state?: string;
}
export namespace TableMonitor {
'use strict';

    export enum StatusEnum {
        Available = 'Available' as any,
        Busy = 'Busy' as any,
        Assigned = 'Assigned' as any,
        Reserved = 'Reserved' as any
    }
}
